language: cpp
dist: trusty
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

before_install:
  - wget https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitPPCupdate.pl
  - wget https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/libogc.7z
  - wget https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/portlibs.7z

install:
  - perl devkitPPCupdate.pl
  - 7z x -y libogc.7z
  - 7z x -y portlibs.7z

script:
  - make