language: c
sudo: required

os:
  - linux

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - wget https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/libogc.7z
  - wget https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/portlibs.7z

install:
  - sudo dpkg --install devkitpro-pacman.deb
  - sudo dkp-pacman --sync --sysupgrade --refresh --needed --noconfirm devkitPPC
  - 7z x -y libogc.7z -o${DEVKITPRO}
  - 7z x -y portlibs.7z -o${DEVKITPRO}

script:
  - make
