name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v1

    - name: Download and install devkitPro
      run: |
        wget -nv https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg --install devkitpro-pacman.deb

    - name: Install required packages
      run: sudo dkp-pacman --sync --sysupgrade --refresh --needed --noconfirm wiiu-dev ppc-jansson

    - name: Build application
      env:
        DEVKITPRO: /opt/devkitpro
        DEVKITPPC: ${DEVKITPRO}/devkitPPC
      run: make

    - name: Move file
      run: mv UsendMii-Client.rpx meta/UsendMii_Client.rpx

    - uses: actions/upload-artifact@master
      with:
        name: UsendMii_Client
        path: meta/
